name: c20Core
version: 1.0-SNAPSHOT
description: Core plugin for all my other plugins
author: caneva20
depend: [Vault]

main: me.caneva20.Core.Core

commands:
  cnv:
    description: 'Shows Core info'
    default: true
  cmd:
    description: 'Foo'
    defaut: true